USE ekspedisi_jne_clone;

CREATE TABLE IF NOT EXISTS provinces (
  province_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  province_code VARCHAR(10) NOT NULL UNIQUE,
  province_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cities (
  city_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  province_id BIGINT UNSIGNED NOT NULL,
  city_code VARCHAR(20) NOT NULL UNIQUE,
  city_name VARCHAR(100) NOT NULL,
  city_type ENUM('KABUPATEN', 'KOTA') NOT NULL DEFAULT 'KOTA',
  postal_code VARCHAR(10) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cities_province
    FOREIGN KEY (province_id) REFERENCES provinces(province_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS districts (
  district_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  city_id BIGINT UNSIGNED NOT NULL,
  district_code VARCHAR(20) NOT NULL UNIQUE,
  district_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_districts_city
    FOREIGN KEY (city_id) REFERENCES cities(city_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS branches (
  branch_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  branch_code VARCHAR(20) NOT NULL UNIQUE,
  branch_name VARCHAR(120) NOT NULL,
  branch_type ENUM('PUSAT', 'CABANG', 'AGEN', 'GUDANG', 'DROPOFF') NOT NULL DEFAULT 'CABANG',
  city_id BIGINT UNSIGNED NOT NULL,
  district_id BIGINT UNSIGNED NULL,
  address TEXT NOT NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(120) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_branches_city
    FOREIGN KEY (city_id) REFERENCES cities(city_id),
  CONSTRAINT fk_branches_district
    FOREIGN KEY (district_id) REFERENCES districts(district_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS customers (
  customer_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customer_code VARCHAR(20) NOT NULL UNIQUE,
  customer_type ENUM('INDIVIDU', 'PERUSAHAAN') NOT NULL DEFAULT 'INDIVIDU',
  full_name VARCHAR(150) NOT NULL,
  company_name VARCHAR(150) NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(120) NULL,
  identity_no VARCHAR(50) NULL,
  tax_no VARCHAR(50) NULL,
  address TEXT NOT NULL,
  city_id BIGINT UNSIGNED NOT NULL,
  district_id BIGINT UNSIGNED NULL,
  postal_code VARCHAR(10) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_customers_city
    FOREIGN KEY (city_id) REFERENCES cities(city_id),
  CONSTRAINT fk_customers_district
    FOREIGN KEY (district_id) REFERENCES districts(district_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS employees (
  employee_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  branch_id BIGINT UNSIGNED NOT NULL,
  employee_code VARCHAR(20) NOT NULL UNIQUE,
  full_name VARCHAR(150) NOT NULL,
  role_name ENUM('ADMIN', 'CS', 'KURIR', 'SORTIR', 'FINANCE', 'SUPERVISOR') NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(120) NULL,
  hire_date DATE NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_employees_branch
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vehicles (
  vehicle_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  branch_id BIGINT UNSIGNED NOT NULL,
  vehicle_code VARCHAR(20) NOT NULL UNIQUE,
  vehicle_type ENUM('MOTOR', 'MOBIL', 'VAN', 'TRUK') NOT NULL,
  plate_number VARCHAR(20) NOT NULL UNIQUE,
  capacity_kg DECIMAL(10,2) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_vehicles_branch
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS service_types (
  service_type_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  service_code VARCHAR(20) NOT NULL UNIQUE,
  service_name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL,
  estimated_min_days INT UNSIGNED NOT NULL,
  estimated_max_days INT UNSIGNED NOT NULL,
  is_cod_available TINYINT(1) NOT NULL DEFAULT 0,
  is_insurance_available TINYINT(1) NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS shipping_rates (
  rate_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  origin_city_id BIGINT UNSIGNED NOT NULL,
  destination_city_id BIGINT UNSIGNED NOT NULL,
  service_type_id BIGINT UNSIGNED NOT NULL,
  base_price DECIMAL(14,2) NOT NULL,
  price_per_kg DECIMAL(14,2) NOT NULL,
  min_charge_kg DECIMAL(10,2) NOT NULL DEFAULT 1,
  lead_time_days INT UNSIGNED NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_shipping_rates_route_service (origin_city_id, destination_city_id, service_type_id),
  CONSTRAINT fk_rates_origin_city
    FOREIGN KEY (origin_city_id) REFERENCES cities(city_id),
  CONSTRAINT fk_rates_destination_city
    FOREIGN KEY (destination_city_id) REFERENCES cities(city_id),
  CONSTRAINT fk_rates_service_type
    FOREIGN KEY (service_type_id) REFERENCES service_types(service_type_id)
) ENGINE=InnoDB;
